sudo: false
language: ruby
rvm:
  - 2.3.4
  - 2.4.1
  - 2.5.0
  - 2.7.2
#before_install:
#  - gem install -v 2.2.17 bundler
script: bundle exec appraisal install && bundle exec appraisal rake && rubocop --fail-level R
