name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
<<<<<<< Updated upstream
=======
    name: Test

>>>>>>> Stashed changes
    runs-on: ubuntu-latest

    strategy:
      matrix:
<<<<<<< Updated upstream
        ruby-version: [2.3.x, 2.4.x, 2.5.x, 2.6.x, 2.7.x]
=======
        ruby-version: [2.3, 2.4, 2.5, 2.6, 2.7]
>>>>>>> Stashed changes

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Install dependencies
        run: bundle install && appraisal install

      - name: Run tests
        run: appraisal rake
